### ISSUE TITLE
cannot specify ControlPlane in envtest.Environment

### ISSUE THREAD

**Issue by ixdy** [kubernetes-sigs/controller-runtime#875]
I think this issue is similar to https://github.com/kubernetes-sigs/controller-runtime/issues/841.

We have some code using `envtest.Environment` that has used the `ControlPlane` field to specify arguments for the `APIServer` and `Etcd` components:

After `sigs.k8s.io/testing_frameworks/integration` was moved into `pkg/internal/testing/integration` in #714, we can no longer do this:

```
use of internal package sigs.k8s.io/controller-runtime/pkg/internal/testing/integration not allowed
```

Is there a better way to be achieving this? Or was this unintentional?

**Comment by rajathagasthya** [comment]
This just needs a release. It was fixed in #846. 

cc @DirectXMan12

**Comment by ixdy** [comment]
@rajathagasthya no, this issue is different; #846 doesn't fix it.

We explicitly want to specify things like the apiserver host/port and etcd host/port.

We had been doing something like
```golang
env := &envtest.Environment {
  ControlPlane: &integration.ControlPlane{
    APIServer: &integration.APIServer{
      URL: apiserverURL,
      EtcdURL: etcdURL,
    },
    Etcd: &integration.Etcd{
      URL: etcdURL,
    },
  },
}
```
etc.

We can no longer do that, since `integration.ControlPlane`, `integration.APIServer`, and `integration.Etcd` are all in an internal package now.

**Comment by ixdy** [comment]
Or for another example, we can't do something like this anymore:
https://github.com/kubernetes-sigs/controller-runtime/blob/8975354b554a084037665f870b133b48aaa5ccea/pkg/internal/testing/integration/internal/integration_tests/integration_test.go#L107-L114

**Comment by rajathagasthya** [comment]
Ah, sorry. I conflated this with the apiserver flags breakage. I don't think integration testing package should be in an internal package since many things there are customizable in an envtest environment. There are multiple breakages to envtest when testing framework was brought into controller-runtime and put into internal package.

**Comment by ixdy** [comment]
cc @hoegaarden 

Was this intentionally put under `pkg/internal` in #749?

**Comment by DirectXMan12** [comment]
agreed here -- those types shouldn't be internal.  Sorry about that.  I think all the shuffling around got things lost in translation.

**Comment by DirectXMan12** [comment]
FWIW, I think the intention was that some of the internal helpers were supposed to be in internal, while the public types stayed exposed externally.  The goal was to eventually unify our `Environment` with th e testing-frameworks config to avoid duplication, but we're not there yet, so re-exposing those types seems like a good idea.

**Comment by DirectXMan12** [comment]
/good-first-issue

should be an easy fix -- just re-export these types.
